### ISSUE TITLE
`npm i` doesn't work due to `Hugo installation failed.`

### ISSUE THREAD

**Issue by SimonBrandner** [matrix-org/matrix-spec#1628]
`npm i` seems to fail on my system:

```
❯ npm i

> matrix-spec@0.0.1 prepare
> npm run get:submodule && npm run _prepare:docsy


> matrix-spec@0.0.1 get:submodule
> git submodule update --init --depth 1


> matrix-spec@0.0.1 _prepare:docsy
> cd themes/docsy && npm install

npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code 1
npm ERR! path /home/simon/Data1/GIT/Matrix/Spec/matrix-spec/themes/docsy/node_modules/hugo-extended
npm ERR! command failed
npm ERR! command sh -c node postinstall.js
npm ERR! ✔ Hugo installed successfully!
npm ERR! ✖ Hugo installation failed. :(
npm ERR! node:internal/errors:496
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! <ref *1> Error: spawnSync /home/simon/Data1/GIT/Matrix/Spec/matrix-spec/themes/docsy/node_modules/hugo-extended/vendor/hugo ENOENT
npm ERR!     at Object.spawnSync (node:internal/child_process:1110:20)
npm ERR!     at spawnSync (node:child_process:871:24)
npm ERR!     at execFileSync (node:child_process:914:15)
npm ERR!     at getBinVersion (file:///home/simon/Data1/GIT/Matrix/Spec/matrix-spec/themes/docsy/node_modules/hugo-extended/lib/utils.js:40:18)
npm ERR!     at install (file:///home/simon/Data1/GIT/Matrix/Spec/matrix-spec/themes/docsy/node_modules/hugo-extended/lib/install.js:51:18)
npm ERR!     at async file:///home/simon/Data1/GIT/Matrix/Spec/matrix-spec/themes/docsy/node_modules/hugo-extended/postinstall.js:4:14 {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawnSync /home/simon/Data1/GIT/Matrix/Spec/matrix-spec/themes/docsy/node_modules/hugo-extended/vendor/hugo',
npm ERR!   path: '/home/simon/Data1/GIT/Matrix/Spec/matrix-spec/themes/docsy/node_modules/hugo-extended/vendor/hugo',
npm ERR!   spawnargs: [ 'version' ],
npm ERR!   error: [Circular *1],
npm ERR!   status: null,
npm ERR!   signal: null,
npm ERR!   output: null,
npm ERR!   pid: 0,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.17.1

npm ERR! A complete log of this run can be found in: /home/simon/.npm/_logs/2023-08-22T19_23_29_283Z-debug-0.log
npm ERR! code 1
npm ERR! path /home/simon/Data1/GIT/Matrix/Spec/matrix-spec
npm ERR! command failed
npm ERR! command sh -c npm run get:submodule && npm run _prepare:docsy

npm ERR! A complete log of this run can be found in: /home/simon/.npm/_logs/2023-08-22T19_23_27_993Z-debug-0.log
```

**Comment by turt2live** [comment]
Looks like it's complaining that `hugo` isn't installed. The extended version will need to be present on your system: https://gohugo.io/installation/

**Comment by SimonBrandner** [comment]
`hugo` is installed on my system:

```
> hugo version
hugo v0.111.3+extended linux/amd64 BuildDate=unknown VendorInfo=nixpkgs
```

It's also super confusing the logs have these two lines (right after each other):

```
npm ERR! ✔ Hugo installed successfully!
npm ERR! ✖ Hugo installation failed. :(
```

**Comment by turt2live** [comment]
The error is very much complaining about lack of hugo. We somewhat recently upgraded to 0.113.0 though - maybe that would help?

**Comment by SimonBrandner** [comment]
I get the same thing with :(

```
❯ hugo version
hugo v0.117.0+extended linux/amd64 BuildDate=unknown VendorInfo=nixpkgs
```

**Comment by turt2live** [comment]
I would suggest using 0.113.0 specifically, as we've had problems with too-new versions in the past.

That said, it should work. I can't replicate this on my machine, and CI appears happy :(
