### ISSUE TITLE
check_examples.py doesn't run on windows

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#330]

**Comment by richvdh** [comment]
`check_examples` got renamed to `check-event-schema-examples.py` by b8dafe86f4d9bf9f81cb623f697381f62ff8a267

@turt2live: is this still a problem?

**Comment by turt2live** [comment]
Very much still broken:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Workspaces\matrix-org\matrix-spec\scripts\check-event-schema-examples.py", line 95, in check_example_file
    jsonschema.validate(example, schema, resolver=resolver)
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\validators.py", line 129, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\validators.py", line 105, in iter_errors
    for error in errors:
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\_validators.py", line 333, in allOf_draft4
    for error in validator.descend(instance, subschema, schema_path=index):
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\validators.py", line 105, in iter_errors
    for error in errors:
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\_validators.py", line 212, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\validators.py", line 375, in resolve
    return url, self._remote_cache(url)
  File "D:\Workspaces\matrix-org\matrix-spec\env\lib\site-packages\jsonschema\validators.py", line 385, in resolve_from_url
    raise RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: [Errno 2] No such file or directory: 'D:\\Workspaces\\matrix-org\\matrix-spec\\data\\event-schemas\\schema\\m.typing.yaml/core-event-schema/event.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Workspaces\matrix-org\matrix-spec\scripts\check-event-schema-examples.py", line 126, in check_example_dir
    check_example_file(examplepath, schemapath)
  File "D:\Workspaces\matrix-org\matrix-spec\scripts\check-event-schema-examples.py", line 97, in check_example_file
    raise ValueError("Error validating JSON schema for %r %r" % (
ValueError: ("Error validating JSON schema for 'D:\\\\Workspaces\\\\matrix-org\\\\matrix-spec\\\\scripts\\\\../data/event-schemas/examples\\\\m.typing.yaml' 'D:\\\\Workspaces\\\\matrix-org\\\\matrix-spec\\\\scripts\\\\../data/event-schemas/schema\\\\m.typing.yaml'", RefResolutionError(FileNotFoundError(2, 'No such file or directory')))
``
